version: '2'

services:
    logger:
        build: .
        image: umputun/docker-logger
        container_name: "logger"
        hostname: "logger"
        restart: always

        logging:
          driver: json-file
          options:
              max-size: "10m"
              max-file: "5"

        environment:
            - LOG_FILES=true
            - LOG_SYSLOG=true
            - EXCLUDE=docker-logger
            - MAX_FILES=10
            - MAX_SIZE=50
            - MAX_AGE=20
            - DEBUG=false
            - TIME_ZONE=America/Los_Angeles
            - SYSLOG_HOST=${SYSLOG_HOST}

        volumes:
            - ${APPDATA_LOCATION}/docker-logger/${INSTANCE_NAME}:/srv/logs
            - /var/run/docker.sock:/var/run/docker.sock
